version: '1.0'

services:
  server:
    build:
      context: ./server
    working_dir: /app
    env_file:
      - .env.development.local
    restart: always
    ports:
      - '80:3000'
    volumes:
      - ./server:/app
    depends_on:
      - rabbitmq
    command: npm run start:dev
  machine:
    build: ./machine
    depends_on:
      - rabbitmq
    command: python3 /machine/receive.py
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  postgres: