version: '1.0'

services:
  server:
    build:
      context: ./server
    working_dir: /app
    env_file:
      - .env.development.local
    restart: always
    expose:
      - '3000'
    depends_on:
      - db
    command: npm run start
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
      #- ./db_data:/docker-entrypoint-initdb.d
    expose:
      - '5432'
    restart: always

volumes:
  postgres: