version: '1.0'

services:
  server:
    build:
      context: ./server
    working_dir: /app
    env_file:
      - .env.development.local
    restart: always
    ports:
      - '80:3000'
      - '8000:8000'
    depends_on:
      - rabbitmq
    networks:
      - network
    command: npm run start

  machine:
    build: ./machine
    depends_on:
      - rabbitmq
    volumes:
      - ./machine:/machine
    networks:
      - network
    restart: always
    command: python3 /machine/main.py

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network

volumes:
  postgres:

networks:
  network: {}